eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
          - Path=/api/product/**
          - Method=GET,POST

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
            - Method=GET,POST

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
            - Method=GET,POST

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
            - Method=GET,POST

        - id: service-registry
          uri: http://localhost:8761
          filters:
            - SetPath=/
          predicates:
            - Path=/eureka

        - id: service-registry-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/spring-boot-microservices-realm









logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: trace
          route:
            RouteDefinitionLocator: info

server:
  port: 8080
